const GENERATE_ACCOUNT = 'GENERATE_ACCOUNT'
const LOAD_ACCOUNT = 'LOAD_ACCOUNT'
const CLEAR_ACCOUNT = 'CLEAR_ACCOUNT'
const REFRESH_ACCOUNT = 'REFRESH_ACCOUNT'
const UPDATE_ACCOUNT_INFO = 'UPDATE_ACCOUNT_INFO'

const TRANSACTION_BEGIN = 'TRANSACTION_BEGIN'
const TRANSACTION_FINISH = 'TRANSACTION_FINISH'
const TRANSACTION_FAIL = 'TRANSACTION_FAIL'
export {
	GENERATE_ACCOUNT,
	LOAD_ACCOUNT,
	CLEAR_ACCOUNT,
	REFRESH_ACCOUNT,
	UPDATE_ACCOUNT_INFO,

	TRANSACTION_BEGIN,
	TRANSACTION_FINISH,
	TRANSACTION_FAIL
}